# NDArray的使用

- 创建
- 常用的属性:shape、size
- 操作，tensor相加，矩阵乘等, reshape, Broadcast等
- 原地操作

API: [NDArray API](https://mxnet.incubator.apache.org/api/python/ndarray.html)

In [1]:
import mxnet as mx
from mxnet import ndarray as nd

MXNet中的NDArray和Numpy中的ndarray基本一致，大多数在ndarray中的用法与函数在NDArray中同样成立。

## 创建

In [2]:
# 直接利用函数创建指定大小的NDArray
print (nd.zeros((3,4), dtype='float32'))
print (nd.ones((3,4), ctx=mx.gpu()))
print (nd.random_normal(shape=(3,4)))


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
<NDArray 3x4 @cpu(0)>

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
<NDArray 3x4 @gpu(0)>

[[ 0.30030754  0.23107235  1.04932892 -0.32433933]
 [-0.0097888   0.73686236  1.72023427  0.46656415]
 [-1.07333767  0.87809837 -0.26717702 -0.8692565 ]]
<NDArray 3x4 @cpu(0)>


In [3]:
import numpy as np
l = [[1,2],[3,4]]
print(nd.array(l)) # 从List转到NDArray
print(nd.array(np.array(l))) # 从np.array转到NDArray


[[ 1.  2.]
 [ 3.  4.]]
<NDArray 2x2 @cpu(0)>

[[ 1.  2.]
 [ 3.  4.]]
<NDArray 2x2 @cpu(0)>


## 常用到的属性

In [4]:
tensor = nd.random_normal(0, 1, shape=(3,4))
print(tensor.shape)
print(tensor.size)

(3, 4)
12


## 操作

In [5]:
shape=(3,4)
x = nd.ones(shape)
y = nd.random_normal(0, 1, shape=shape)

In [6]:
x + y # 逐元素相加


[[ 1.79687119  1.85240507  1.61860609  1.47654879]
 [ 1.74863517  1.55032933  0.77433252 -1.11320662]
 [ 0.04251927  1.3256073   0.05152243  1.77750111]]
<NDArray 3x4 @cpu(0)>

In [7]:
x * y # 逐元素相乘


[[ 0.79687113  0.85240501  0.61860603  0.47654876]
 [ 0.74863517  0.55032933 -0.22566749 -2.11320662]
 [-0.95748073  0.32560727 -0.94847757  0.77750117]]
<NDArray 3x4 @cpu(0)>

In [8]:
nd.exp(y) # 每个元素取指数


[[ 2.21858835  2.34528041  1.8563385   1.61050653]
 [ 2.11411262  1.7338239   0.79798341  0.12084983]
 [ 0.38385871  1.38487136  0.38733026  2.17602801]]
<NDArray 3x4 @cpu(0)>

In [9]:
nd.dot(x, y.T) # 矩阵乘


[[ 2.74443078 -1.0399096  -0.80284995]
 [ 2.74443078 -1.0399096  -0.80284995]
 [ 2.74443078 -1.0399096  -0.80284995]]
<NDArray 3x3 @cpu(0)>

In [10]:
# Reshape
nd.arange(0,9).reshape((3,3))


[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]]
<NDArray 3x3 @cpu(0)>

## 原地操作

In [11]:
x = x + y # x的内存地址变化了
x[:] = x + y # x的内存地址不变
x += y # x的内存地址不变
x


[[ 3.39061356  3.55721521  2.85581827  2.42964625]
 [ 3.2459054   2.6509881   0.32299757 -5.33961964]
 [-1.87244225  1.9768219  -1.84543276  3.33250332]]
<NDArray 3x4 @cpu(0)>

## Broadcasting

In [12]:
z = nd.ones(shape=(4,))
print("x's shape is {0}\nz's shape is {1}".format(x.shape, z.shape))
x + z

x's shape is (3, 4)
z's shape is (4,)



[[ 4.39061356  4.55721521  3.85581827  3.42964625]
 [ 4.2459054   3.6509881   1.32299757 -4.33961964]
 [-0.87244225  2.9768219  -0.84543276  4.33250332]]
<NDArray 3x4 @cpu(0)>